test:
    script:
        - mkdir ~/R_libs
        - export R_LIBS="/home/$USER/R_libs"
        - Rscript -e "install.packages('devtools')"
        - make test

mirror:
    script:
        - git push --mirror git@github.com:PoisotLab/betalink.git
