stages:
    - test
    - mirror

test:
    stage: test
    script:
        - mkdir -p ~/R_libs
        - export R_LIBS="/home/$USER/R_libs"
        - Rscript -e "install.packages(c('testthat', 'covr', 'roxygen2', 'devtools', 'plyr', 'igraph', 'stringr'), repos='http://cran.rstudio.com')"
        - make test

mirror:
    stage: mirror
    script:
        - git push --mirror git@github.com:PoisotLab/betalink.git
